"""initial tables

Revision ID: d4f887943551
Revises: 
Create Date: 2026-02-14 07:09:05.867129
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f887943551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsdesk_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('is_team_related', sa.Boolean(), nullable=True),
    sa.Column('related_stocks', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('connected_clusters', sa.JSON(), nullable=True),
    sa.Column('ai_article', sa.Text(), nullable=True),
    sa.Column('relation_map', sa.JSON(), nullable=True),
    sa.Column('news_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_clusters_id'), 'news_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_news_clusters_newsdesk_date'), 'news_clusters', ['newsdesk_date'], unique=False)
    op.create_table('newsdesk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_time', sa.String(length=5), nullable=False),
    sa.Column('overall_sentiment', sa.Float(), nullable=True),
    sa.Column('total_clusters', sa.Integer(), nullable=True),
    sa.Column('total_news', sa.Integer(), nullable=True),
    sa.Column('clusters_data', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsdesk_snapshots_id'), 'newsdesk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_newsdesk_snapshots_snapshot_date'), 'newsdesk_snapshots', ['snapshot_date'], unique=False)
    op.create_table('raw_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('newsdesk_date', sa.Date(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_raw_news_id'), 'raw_news', ['id'], unique=False)
    op.create_index(op.f('ix_raw_news_newsdesk_date'), 'raw_news', ['newsdesk_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_news_newsdesk_date'), table_name='raw_news')
    op.drop_index(op.f('ix_raw_news_id'), table_name='raw_news')
    op.drop_table('raw_news')
    op.drop_index(op.f('ix_newsdesk_snapshots_snapshot_date'), table_name='newsdesk_snapshots')
    op.drop_index(op.f('ix_newsdesk_snapshots_id'), table_name='newsdesk_snapshots')
    op.drop_table('newsdesk_snapshots')
    op.drop_index(op.f('ix_news_clusters_newsdesk_date'), table_name='news_clusters')
    op.drop_index(op.f('ix_news_clusters_id'), table_name='news_clusters')
    op.drop_table('news_clusters')
    # ### end Alembic commands ###
